#!/bin/bash

python clean.py image_test_64_by_64.txt
mv image_test_64_by_64.txt_clean image_test_64_by_64_clean
python convert_unsigned_decimal_to_binary.py image_test_64_by_64_clean

python clean.py self_smoothed_image_test_64_by_64.txt
mv self_smoothed_image_test_64_by_64.txt_clean self_smoothed_image_test_64_by_64_clean
python convert_unsigned_decimal_to_binary.py self_smoothed_image_test_64_by_64_clean

python clean.py equalized_self_smoothed_image_test_64_by_64.txt
mv equalized_self_smoothed_image_test_64_by_64.txt_clean equalized_self_smoothed_image_test_64_by_64_clean
python convert_unsigned_decimal_to_binary.py equalized_self_smoothed_image_test_64_by_64_clean

python clean.py equalized_image_test_64_by_64.txt
mv equalized_image_test_64_by_64.txt_clean equalized_image_test_64_by_64_clean
python convert_unsigned_decimal_to_binary.py equalized_image_test_64_by_64_clean

python clean.py self_smoothed_equalized_image_test_64_by_64.txt
mv self_smoothed_equalized_image_test_64_by_64.txt_clean self_smoothed_equalized_image_test_64_by_64_clean
python convert_unsigned_decimal_to_binary.py self_smoothed_equalized_image_test_64_by_64_clean
