cp /home/sxn013/TSMC/GRNN/components/reg_gen.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/work/NCL_signals.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/work/MTNCL_tree_functs.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/work/MTNCL_treecomps.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/th22m_en_gen.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/mux_21_gen.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/mux_21_nic.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/mux_21_gen_nic.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/MUX21_dr_gen.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/Mult_of_checkV2.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/SDC_w_EN.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/MUX21_gen.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/reg_zero_res.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/reg_null_res.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/adding_units.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/work/MTNCL_completion.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/adder_gen.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/regs_gen_null_res.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/reg_gen_zero_res.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/counter_selfReset.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/shiftRegister.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/decoder_gen.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/compm_half_sel.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/mux_nto1_gen.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/mult_acc_of_check_8.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/mult_of_check_8.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/TwoPhaseCounter.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/Baugh_Wooley_gen.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/Add_of_checkV2.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/accumulator_outputOnReset.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/TimesZeroCheck.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/elem_adder.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/one_elem_adder.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/one_elem_mult.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/one_elem_mult_8.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/one_elem_sub_reverse.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/sub_of_check.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/subtractor_gen.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/elem_mult_8.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/elem_mult.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/wrap_LUT_sigmoid_8.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/wrap_LUT_sigmoid.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/wrap_LUT_tanh_8.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/wrap_elem_mult.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/wrap_elem_mult_8.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/wrap_elem_adder_8.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/wrap_elem_adder.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/multiply_of_accumulate_8.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/multiply_of_accumulate.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/wrap_multiply_of_accumulate_8.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/wrap_multiply_of_accumulate.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/wrap_LUT_tanh.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/wrap_one_elem_sub_8_reverse.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/wrap_one_elem_sub_reverse.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/wrap_one_elem_mult_8.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/wrap_one_elem_mult.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/wrap_one_elem_adder_8.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/wrap_one_elem_adder.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/OAAT_out_all_in_forever.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/OAAT_in_all_out.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/wrap_LUT_tanh.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/wrap_LUT_tanh_8.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/wrap_LUT_sigmoid.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/wrap_LUT_sigmoid_8.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/LUT_tanh_8_16.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/LUT_sigmoid_8_16.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/memWriteCounter.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/addressGen.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/adder_8_16.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/one_adder_8_16.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/one_mult_8_16.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/one_sub_8_16_reverse.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/mult_of_accumulate_8_16.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/convert_8_16.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/convert_16_8.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/mult_8_16.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/RCF_OAAT_in_all_out.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/RCF_OAAT_out_all_in_RPT.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/RCF_OAAT_out_all_in_128.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/RCF_OAAT_out_all_in_128_RPT.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/RCF_OAAT_out_all_in_128_forever.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/flashAccessGRNN.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/flashToMemGRNN.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/RCF_GRNN_fc_layer.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/GRNN_top_w_mem.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/GRNN_control_w_mem.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/GRNN_w_IO.vhd /home/mtennant/Projects/GRNN_w_IO_WrapperTest/

cp /home/mtennant/Projects/GRNN_Questa_test1/*.rcf /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
cp /home/mtennant/Projects/GRNN_Questa_test1/*.v /home/mtennant/Projects/GRNN_w_IO_WrapperTest/
