onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/maxBitwidth
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/maxLayerSize
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/numberLayers
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/inputWidth
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/layerBitwidth
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/layerSize
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/layerType
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/fcNumberLayers
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/fcLayerBitwidth
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/trunc_zt
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/trunc_htm1_zt
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/trunc_zeta
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/trunc_rt
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/trunc_htm1_rt
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/trunc_sht
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/trunc_ztm1_sht
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/trunc_bitchange
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/trunc_fc
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/configDataRequest
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/configDataReady
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/Xt
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/reset
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/inDataReady
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/outDataReceived
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/DO
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/cs
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/clk
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/DIO
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/outDataIsReady
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/dataRequest
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/z
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/flashKi
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/flashSleep
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/inputReady
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/mem_data_ko_zt
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/mem_data_sleep_in_Zt
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/mem_data_ko_rt
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/mem_data_sleep_in_Rt
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/mem_data_ko_sht
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/mem_data_sleep_in_Sht
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/mem_data_ko_zt_B
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/mem_data_sleep_in_Zt_B
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/mem_data_ko_rt_B
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/mem_data_sleep_in_Rt_B
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/mem_data_ko_sht_B
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/mem_data_sleep_in_Sht_B
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/mem_data_ko_ZetaNu
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/mem_data_sleep_in_ZetaNu
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/mem_data_ko_FC
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/mem_data_sleep_in_FC
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/MainSleepIn
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/MainKo
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/sdc_en
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/configSleepIn
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/configDataReady_delay
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/configDataRequest_temp
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/ZetaNuSleepOut
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/fcKo
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/MainConfigKo
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/sleepOutGRNN
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/notOutDataReceived
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/notOutDataIsReady
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/dataRequest_temp
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/prevLayerSize
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/layerIsInput
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/nextLayerBitwidth
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/trunc_bitchange_3
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/a_sr
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/writeEn
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/data1
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/X_fill_data
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/const7
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/flashData
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/mem_data_Zt
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/mem_data_Rt
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/mem_data_Sht
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/mem_data_Zt_B
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/mem_data_Rt_B
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/mem_data_Sht_B
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/mem_data_ZetaNu
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/mem_data_FC
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/MainXt
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/z_dr
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/flashCount
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/configPorts
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/configBitsIn_sr
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/configBitsIn
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/configBits
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/ZetaNu
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/MainOut
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/Xt_Fill
add wave -noupdate -group GRNN_w_io /tb_grnn_gru_8_16/uut/data_out_ready_pre
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/ki
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/reset
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/DO
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/cs
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/clk
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/DIO
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/sleep_out
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/inputReady
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/count_out
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/z
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/clk_temp
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/counter_ko
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/counter_ki
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/DIO_pre
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/DIO_pre1
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/counter32
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/inv_clk
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/clk_inv
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/sdc_en
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/clk_temp_pre
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/counter_sleep_out
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/setOfSixteen01_1
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/setOfSixteen23_1
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/setOfSixteen01_0
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/setOfSixteen23_0
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/clk_and_32
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/sleep_out_temp
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/counter_ki_temp
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/sdc_en_temp
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/sdc_en_and_ki
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/counter_ki_pre
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/inputReady_temp
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/shift_reg_out
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/bits_out
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/accumulate_reset
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/data0
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/data1
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/setOfSixteen
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/counter_bits
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/const_723136
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/inv_clk_delay
add wave -noupdate -group flashAccess /tb_grnn_gru_8_16/uut/flashAccess/clk_inv_delay
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/count_in
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/data_in
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/reset
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/sleep_in
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/mem_data_ko_Zt
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/mem_data_Zt
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/mem_data_sleep_in_Zt
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/mem_data_ko_Rt
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/mem_data_Rt
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/mem_data_sleep_in_Rt
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/mem_data_ko_Sht
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/mem_data_Sht
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/mem_data_sleep_in_Sht
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/mem_data_ko_Zt_B
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/mem_data_Zt_B
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/mem_data_sleep_in_Zt_B
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/mem_data_ko_Rt_B
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/mem_data_Rt_B
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/mem_data_sleep_in_Rt_B
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/mem_data_ko_Sht_B
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/mem_data_Sht_B
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/mem_data_sleep_in_Sht_B
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/mem_data_ko_ZetaNu
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/mem_data_ZetaNu
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/mem_data_sleep_in_ZetaNu
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/mem_data_ko_FC
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/mem_data_FC
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/mem_data_sleep_in_FC
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/inputReady
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/ko
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/ZtDone_not
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/kiMux1_out
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/RtXorZt
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/kiMux2_out
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/ShtXorRt
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/kiMux3_out
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/Zt_BXorSht
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/kiMux4_out
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/kiMux5_out
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/kiMux6_out
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/kiMux7_out
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/Rt_BXorZt_B
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/Sht_BXorRt_B
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/ZetaNuXorSht_B
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/FCXorZetaNu
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/comp_ki
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/ZtMatch
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/ZtDone
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/RtMatch
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/RtDone
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/RtDone_not
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/comp_a_out
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/ShtMatch
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/ShtDone
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/ShtDone_not
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/Zt_BDone
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/Zt_BMatch
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/Zt_BDone_not
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/Rt_BMatch
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/Rt_BDone
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/Rt_BDone_not
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/Sht_BMatch
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/Sht_BDone
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/Sht_BDone_not
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/ZetaNuMatch
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/ZetaNuDone
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/ZetaNuDone_not
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/FCMatch
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/FCDone
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/FCDone_not
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/ZtNotMatch
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/zt_sleep_sel
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/RtNotMatch
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/rt_sleep_sel
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/ShtNotMatch
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/sht_sleep_sel
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/Zt_BNotMatch
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/zt_b_sleep_sel
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/Rt_BNotMatch
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/rt_b_sleep_sel
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/Sht_BNotMatch
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/sht_b_sleep_sel
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/ZetaNuNotMatch
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/ZetaNu_sleep_sel
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/FCNotMatch
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/FC_sleep_sel
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/reg_a_in
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/reg_a_out
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/data0
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/data1
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/Zt_data_sel
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/Rt_data_sel
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/Sht_data_sel
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/Zt_B_data_sel
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/Rt_B_data_sel
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/Sht_B_data_sel
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/ZetaNu_data_sel
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/FC_data_sel
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/Zt_data_en_out
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/Rt_data_en_out
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/Sht_data_en_out
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/Zt_B_data_en_out
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/const_0
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/Rt_B_data_en_out
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/Sht_B_data_en_out
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/ZetaNu_data_en_out
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/FC_data_en_out
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/const_14466
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/const_28930
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/const_43394
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/const_43906
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/const_44418
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/const_44930
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/const_44938
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/const_45196
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/count_equal_Zt
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/count_equal_Rt
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/count_equal_Sht
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/count_equal_Zt_B
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/count_equal_Rt_B
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/count_equal_Sht_B
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/count_equal_ZetaNu
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/count_equal_FC
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/and_tree_in_Zt
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/or_tree_in_Zt
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/and_tree_in_Rt
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/or_tree_in_Rt
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/and_tree_in_Sht
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/or_tree_in_Sht
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/and_tree_in_Zt_B
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/or_tree_in_Zt_B
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/and_tree_in_Rt_B
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/or_tree_in_Rt_B
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/and_tree_in_Sht_B
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/or_tree_in_Sht_B
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/and_tree_in_ZetaNu
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/or_tree_in_ZetaNu
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/and_tree_in_FC
add wave -noupdate -group flashToMem /tb_grnn_gru_8_16/uut/flashToMem/or_tree_in_FC
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/numberLayers
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/inputWidth
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/layerBitwidth
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/layerSize
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/layerType
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/layerIsInput
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/prevLayerSize
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/nextLayerBitwidth
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/trunc_zt
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/trunc_htm1_zt
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/trunc_zeta
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/trunc_rt
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/trunc_htm1_rt
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/trunc_sht
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/trunc_ztm1_sht
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/trunc_bitchange
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/config_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/config_sleep_in
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/zeta
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/nu
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Xt
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/reset
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/sleep_in
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/ki
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_B_in
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_B_in_sleep_in
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_B_in_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_B_in
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_B_in_sleep_in
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_B_in_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_B_in
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_B_in_sleep_in
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_B_in_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_W
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_sleep_in
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_W
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_sleep_in
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_W
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_sleep_in
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/writeEn
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/sleep_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/z
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/configBitsIn
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/configBits_reg
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/counterBits_prev
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/counterBits
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/const511
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/const63
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/const127
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/const63_127
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_layer_0_count
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_layer_1_count
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_layer_2_count
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_layer_3_count
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_layer_0_count
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_layer_1_count
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_layer_2_count
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_layer_3_count
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_layer_0_count
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_layer_1_count
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_layer_2_count
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_layer_3_count
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/config_acc_reset
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Xt_select
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/data0
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Xt_ko_select
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_layer_0_accReset
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_layer_1_accReset
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_layer_2_accReset
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_layer_3_accReset
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/data1
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_layer_0_accReset
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_layer_1_accReset
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_layer_2_accReset
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_layer_3_accReset
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_layer_0_accReset
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_layer_1_accReset
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_layer_2_accReset
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_layer_3_accReset
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/configBits
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/configBits_prev
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Xt_next
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Ht_next_reg_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Xt_next_reg_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Ht_next_reg_out_zero
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Htm1_next_reg_0_in
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Htm1_next_reg_1_in
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Htm1_next_reg_2_in
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Htm1_next_reg_3_in
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Htm1_next_reg_0_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Htm1_next_reg_1_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Htm1_next_reg_2_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Htm1_next_reg_3_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Main_Htm1
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Main_Xt
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Xt_next_mux_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Ht_next_8
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Ht_next_16
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Ht_next_reg_8_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Ht_next_reg_16_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_layer_0_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_layer_1_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_layer_2_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_layer_3_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_B
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_layer_0_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_layer_1_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_layer_2_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_layer_3_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_B
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_layer_0_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_layer_1_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_layer_2_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_layer_3_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_B
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_layer_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_layer_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_layer_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/layerNumber
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/numberLayers_ext
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Ht_next_reg_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/config_sleep_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Main_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Xt_next_reg_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Main_ko_select_0
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Main_ko_select_1
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Main_ko_select_2
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Main_ko_select_3
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Htm1_next_reg_0_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/configBits_select_0
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Ht_next_en_1_en
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Ht_next_en_2_en
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Ht_next_en_3_en
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Htm1_next_reg_1_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/configBits_select_1
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/configBits_select_2
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/configBits_select_3
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Htm1_next_reg_2_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Htm1_next_reg_3_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Main_sleep_in
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Main_sleep_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/ht_reg_ki
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Ht_next_reg_ko_b
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Ht_next_reg_ko_c
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/runCounterko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/runCounter_sleep_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/ht_next_reg_ki
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Htm1_next_reg_0_ko_lower
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Htm1_next_reg_0_ko_upper
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Htm1_next_reg_0_ko_mux
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Htm1_next_reg_1_ko_lower
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Htm1_next_reg_1_ko_upper
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Htm1_next_reg_1_ko_mux
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Htm1_next_reg_2_ko_lower
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Htm1_next_reg_2_ko_upper
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Htm1_next_reg_2_ko_mux
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Htm1_next_reg_3_ko_lower
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Htm1_next_reg_3_ko_upper
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Htm1_next_reg_3_ko_mux
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/ht_next_reg_ki_and
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Xt_next_reg_ko_lower
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Xt_next_reg_ko_upper
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Xt_next_reg_ko_mux
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_in_OAAT_ki
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_in_OAAT_sleep_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_layer_0_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_layer_1_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_layer_2_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_layer_3_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_layer_0_ki
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_layer_0_sleep_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_B_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_layer_1_ki
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_layer_1_sleep_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_layer_2_ki
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_layer_2_sleep_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_layer_3_ki
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_layer_3_sleep_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_layer_01_sleep_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_layer_23_sleep_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_bias_layer_sleep_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/layerNumberIsNull
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Zt_B_sleep_in
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_in_OAAT_ki
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_in_OAAT_sleep_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_layer_0_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_layer_1_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_layer_2_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_layer_3_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_layer_0_ki
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_layer_0_sleep_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_B_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_layer_1_ki
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_layer_1_sleep_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_layer_2_ki
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_layer_2_sleep_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_layer_3_ki
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_layer_3_sleep_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_layer_01_sleep_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_layer_23_sleep_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_bias_layer_sleep_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Rt_B_sleep_in
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_in_OAAT_ki
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_in_OAAT_sleep_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_layer_0_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_layer_1_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_layer_2_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_layer_3_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_layer_0_ki
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_layer_0_sleep_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_B_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_layer_1_ki
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_layer_1_sleep_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_layer_2_ki
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_layer_2_sleep_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_layer_3_ki
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_layer_3_sleep_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_layer_01_sleep_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_layer_23_sleep_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_bias_layer_sleep_out
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Sht_B_sleep_in
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Xt_ko_select_real
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Ht_next_reg_8_ko_a_lower
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Ht_next_reg_8_ko_a_upper
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Ht_next_reg_16_ko_a_lower
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Ht_next_reg_16_ko_a_upper
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Ht_next_reg_8_ko_a_mux
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Ht_next_reg_8_ko
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Ht_next_reg_16_ko_a_mux
add wave -noupdate -group GRNN_Main /tb_grnn_gru_8_16/uut/GRNN_Main/Ht_next_reg_16_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/layerBitwidth
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/layerSize
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/layerType
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/layerIsInput
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/prevLayerSize
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/layerNumber
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/zeta
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/nu
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Xt
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Ht
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/reset
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/sleep_in
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/ki
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Zt_B
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Zt_B_sleep_in
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Zt_B_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Rt_B
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Rt_B_sleep_in
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Rt_B_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Sht_B
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Sht_B_sleep_in
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Sht_B_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Zt_W
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Zt_sleep_in
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Zt_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Rt_W
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Rt_sleep_in
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Rt_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Sht_W
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Sht_sleep_in
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Sht_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/writeEn
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/trunc_zt
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/trunc_htm1_zt
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/trunc_zeta
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/trunc_rt
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/trunc_htm1_rt
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/trunc_sht
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/trunc_ztm1_sht
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/trunc_bitchange
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/z_8
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/z_16
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/data0
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/data1
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/xh_oaat_acc_reset
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/htm1_for_zt_acc_reset
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/htm1_for_rt_acc_reset
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/sh_xh_oaat_acc_reset
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/zt_pre_bias_reg_out_acc_reset
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/xh_oaat_lowerIsMax
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/xh_oaat_upperIsMax
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/sh_xh_oaat_lowerIsMax
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/sh_xh_oaat_upperIsMax
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/ko_grnn
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/layerSize_or_prevLayerSize
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/layerSize_xor_prevLayerSize
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/htm1_for_zt_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/xh_oaat_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/htm1_for_rt_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/xt_sh_reg_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/ko_gru
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/xh_oaat_ki
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/xh_oaat_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/zt_mult_of_acc_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/sht_mult_of_acc_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/xh_ki_gru
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/zt_mult_of_ki
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/zt_mult_of_acc_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/zt_bias_adder_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/sht_bias_adder_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/sht_mult_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/zt_ko_grnn
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/zt_bias_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/zt_LUT_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/htm1_zt_mult_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/one_minus_zt_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/zt_LUT_ki
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/zt_LUT_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/htm1_for_zt_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/ht_adder_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/htm1_zt_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/zeta_mult_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/one_minus_ki
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/one_minus_zt_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/nu_adder_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/zeta_mult_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/nu_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_acc_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_acc_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_LUT_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_bias_adder_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_bias_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_htm1_mult_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_LUT_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/htm1_for_rt_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_htm1_mult_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_htm1_reg_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/sh_xh_oaat_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_htm1_reg_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/xt_sh_reg_bottom64
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/xt_sh_reg_lower64
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/bottom64_lower64
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/sht_mult_sleep_in
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/sh_xh_oaat_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/sht_mult_of_acc_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/sht_zt_mux_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/sht_LUT_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/sht_bias_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/sht_LUT_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/one_minus_z_mux_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/sht_mult_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/output_reg_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/ht_adder_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/output_reg_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/zt_pre_bias_reg_in_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/zt_pre_bias_reg_out_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/zt_pre_bias_reg_in_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/zt_pre_bias_reg_out_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/gen_comp_units_sleep_in
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/zt_addr_mult_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_addr_mult_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/zt_memAddress_R_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/zt_memAddress_W_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/zt_memAddress_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_memAddress_R_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_memAddress_W_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_memAddress_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_acc_sleep_in_a
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/sht_memAddress_R_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/sht_memAddress_W_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/sht_memAddress_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/sht_addr_mult_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Zt_weightMem_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Zt_weightMem_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Rt_weightMem_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Rt_weightMem_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Sht_weightMem_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Sht_weightMem_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/mux16_sleep
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/mux8_sleep
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/output_reg_8_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/output_reg_16_ko
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/output_reg_8_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/output_reg_16_sleep_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/xt_sh_reg_tree
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Zt_address_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Rt_address_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Sht_address_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/const63
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/const64
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/const127
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/const128
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/const191
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/const255
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/const63_127
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/inputLayer_64_128
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/layer_127_255
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/layer_191
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/const_acc_value
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/xh_oaat_count
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/sh_xh_oaat_count
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Zt_weightMem_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Rt_weightMem_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Sht_weightMem_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_htm1_reg_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/Xt_sh_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/zt_pre_bias_oaat_between
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/htm1_for_zt_count
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/htm1_for_rt_count
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/zt_pre_bias_reg_out_count
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/xh_oaat_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/zt_pre_bias
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/zt_bias_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/zt
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/htm1_for_zt
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/htm1_zt_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/const1_8bit
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/const1_16bit
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/one_mux_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/one_minus_zt
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/zeta_mult_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/nu_adder_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/one_minus_z_mux_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_pre_bias
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_bias_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/htm1_rt
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_htm1_mult_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/sh_xh_oaat_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/sht_pre_bias
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/sht_bias_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/sht_zt_mux_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/sht
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/sht_mult_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/ht_adder_out
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/zt_pre_bias_oaat_in
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/ht_adder_out_bottom8_replace
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/output_mux_in_16
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/output_reg_16_in
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/output_mux_in_8
add wave -noupdate -group GRNN_Computation /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/output_reg_8_in
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/a
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/b
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/RCF_width
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/reset_count
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/reset
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/sleep_in_a
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/sleep_in_b
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/trunc
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/ki
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/ko
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/sleep_out
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/z
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/input_reg_in
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/input_reg_out
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_out
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_16_out
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8_out
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/sleep_in
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/input_reg_sleep_a
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/input_reg_sleep_b
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/input_reg_sleep
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/comp_out_out
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_ko
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8_ko
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_16_ko
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_sleep_out
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8_sleep_out
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_16_sleep_out
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/RCF_width_dr
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/sleep_in_8
add wave -noupdate -group rt_mult_of_accumulate /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/sleep_in_16
add wave -noupdate -group mult_8 /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/a
add wave -noupdate -group mult_8 /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/b
add wave -noupdate -group mult_8 /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/reset_count
add wave -noupdate -group mult_8 /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/reset
add wave -noupdate -group mult_8 /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/sleep_in_a
add wave -noupdate -group mult_8 /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/sleep_in_b
add wave -noupdate -group mult_8 /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/trunc
add wave -noupdate -group mult_8 /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/ki
add wave -noupdate -group mult_8 /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/ko
add wave -noupdate -group mult_8 /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/sleep_out
add wave -noupdate -group mult_8 /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/z
add wave -noupdate -group mult_8 /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/a_buf
add wave -noupdate -group mult_8 /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/b_buf
add wave -noupdate -group mult_8 /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/z_buf
add wave -noupdate -group mult_8 /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/reset_count_buf
add wave -noupdate -group mult_8 /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/trunc_buf
add wave -noupdate -group mult_8 /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/sleep_in_a_buf
add wave -noupdate -group mult_8 /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/sleep_in_b_buf
add wave -noupdate -group mult_8 /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/ki_buf
add wave -noupdate -group mult_8 /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/ko_buf
add wave -noupdate -group mult_8 /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/sleep_out_buf
add wave -noupdate -group mult_of_acc /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/mult_of_acc/reset_count
add wave -noupdate -group mult_of_acc /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/mult_of_acc/input_reg_in
add wave -noupdate -group mult_of_acc /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/mult_of_acc/acc_out
add wave -noupdate -group mult_of_acc /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/mult_of_acc/input_reg_out
add wave -noupdate -group mult_of_acc /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/mult_of_acc/mult_out
add wave -noupdate -group mult_of_acc /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/mult_of_acc/trunc_out
add wave -noupdate -group mult_of_acc /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/mult_of_acc/sleep_in
add wave -noupdate -group mult_of_acc /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/mult_of_acc/input_reg_sleep_a
add wave -noupdate -group mult_of_acc /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/mult_of_acc/input_reg_sleep_b
add wave -noupdate -group mult_of_acc /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/mult_of_acc/input_reg_sleep
add wave -noupdate -group mult_of_acc /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/mult_of_acc/comp_out_out
add wave -noupdate -group mult_of_acc /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/mult_of_acc/acc_ko
add wave -noupdate -group mult_of_acc /tb_grnn_gru_8_16/uut/GRNN_Main/GRNN_Computation/rt_mult_of_accumulate/mult_8/mult_of_acc/acc_sleep_out
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 271
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {906 ps}
