onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/mem_data
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/read_address
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/write_en
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/standard_read_en
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/parallelism_en
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/opCode_signal
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/reset_signal
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/ko_signal
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/ki_signal
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/sleepin_signal
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/sleepout_signal
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/S_signal
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/temp_5
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/CORRECT
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/checker
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/Icheck
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/slowIcheck
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/data_0
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/data_1
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/opCode
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/mem_data
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/read_address
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/write_en
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/standard_read_en
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/parallelism_en
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/ki
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/sleep
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/rst
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/sleepOut
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/ko
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/output
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/data_0
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/data_1
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/reset_count
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/roundedPixelRegister
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/reset_count_plus_one
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/inputHEQMUX
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/inputSFMUX
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/globalOutput
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/inputHEQ
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/inputSF
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/outputSF
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/outputHEQ
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/sleep_SF
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/sleep_HEQ
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/sleepOut_HEQ
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/sleepOut_SF
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/ki_SF
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/ki_HEQ
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/ko_HEQ
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/ko_SF
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/sleep_global_00
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/sleep_global_01
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_input
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/image_loaded
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/image_stored
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_ko
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_sleep_in
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_ki
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/image_store_load_instance/mem_data
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/image_store_load_instance/read_address
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/image_store_load_instance/write_en
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/image_store_load_instance/standard_read_en
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/image_store_load_instance/parallelism_en
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/image_store_load_instance/reset
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/image_store_load_instance/ki
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/image_store_load_instance/ko
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/image_store_load_instance/sleep_in
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/image_store_load_instance/sleep_out
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/image_store_load_instance/image_loaded
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/image_store_load_instance/image_stored
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/image_store_load_instance/z
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/image_store_load_instance/ko_image_store
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/image_store_load_instance/ko_image_load
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/image_store_load_instance/image_stored_and_std_read_enable
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/image_store_load_instance/image_stored_image_store
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/image_store_load_instance/sleepout_image_load
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/image_store_load_instance/sleepin_image_store
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/image_store_load_instance/sleepin_image_load
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/image_store_load_instance/address
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/image_store_load_instance/sram_address
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/image_store_load_instance/input_sram
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/image_store_load_instance/write_en_inputs
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/image_store_load_instance/standard_read_en_vector
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/image_store_load_instance/read_address_sram
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/opCode
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/input
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/ki
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/sleep
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/rst
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/sleepOut
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/ko
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/output
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/data_0
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/data_1
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/reset_count
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/roundedPixelRegister
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/reset_count_plus_one
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/inputHEQMUX
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/inputSFMUX
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/globalOutput
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/inputHEQ
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/inputSF
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/outputSF
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/outputHEQ
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/sleep_SF
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/sleep_HEQ
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/sleepOut_HEQ
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/sleepOut_SF
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/ki_SF
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/ki_HEQ
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/ko_HEQ
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/ko_SF
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/sleep_global_00
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/sleep_global_01
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/ko_global_00
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/ko_global_01
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/input
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/ki
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/sleep
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/rst
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/sleepOut
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/ko
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/output
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/data_0
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/data_1
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/accReset
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/accReset_1
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/roundedPixelRegister
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/reset_count
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/reset_count_plus_one
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/reset_count_plus_one_plus_one
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/not_accReset
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/ko_trial
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/kos
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/sleeps
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/hold
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/accReg
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/non_repeatable_register_count
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/non_repeatable_register_count_0
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/non_repeatable_register_count_1
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/count_equal
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/newShadeValues
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/shade_counter_output
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/sleep_out_1
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/ko_1
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/ko_0
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/sleep_out_2
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/ko_2
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/new_input
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/accReset_00
add wave -noupdate /tb_mtncl_cu_heq_64_by_64_image_store_load/uut/control_unit_instance/mtncl_heq_instance/not_accReset_00
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {698786670 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 590
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ms
update
WaveRestoreZoom {698139581 ps} {699288019 ps}
